language: php
matrix:
  include:
  - php: 8.1
  - php: 8.2
  - php: 8.3
  fast_finish: true
  allow_failures:
  - php: 8.3

install:
- composer install --prefer-dist --no-interaction --no-progress

script:
- vendor/bin/phpunit tests/MarkdownTest.php
